import { Story } from "@storybook/react";
import React, { ComponentProps, useEffect } from "react";
import VariantSearchBox from "./VariantSearchBox";


const storyExport = {
  title: "VariantSearchBox",
  component: VariantSearchBox,
};
export default storyExport;

const Template: Story<ComponentProps<typeof VariantSearchBox>> = (args) => (
  <VariantSearchBox {...args} />
);

export const Default = Template.bind({});
Default.args = {
  data: [
    "North Campus Restrooms Building",
    "Peterson Hall",
    "RIMAC",
    "Medical Teaching Facility",
    "Stuart Collection Storage",
    "Canyonview Rec/Athletics Administration",
    "Center for Memory and Recording Research",
    "Career Services Center",
    "Jacobs Hall",
    "Engineering Building Unit II",
    "Institute of the Americas Building",
    "Center for Neural Circuits and Behavior",
    "San Diego Supercomputer Center",
    "George Palade Laboratories for Cellular and Molecular Medicine",
    "High Bay Physics Laboratory",
    "Kelp",
    "University Center 214",
    "University Center 215",
    "University Center 112",
    "Robinson Building 1 - Administration",
    "Powell Structural Systems Laboratory",
    "Stein Clinical Research Building",
    "Perlman Ambulatory Care Unit",
    "Shiley Eye Institute",
    "Clinical Research Facility",
    "School of Medicine Building 4",
    "Thornton Pavilion",
    "Joan and Irwin Jacobs Center for La Jolla Playhouse",
    "Che Cafe",
    "University Center 965",
    "School of Medicine Building 1",
    "School of Medicine Building 3",
    "Warren Lecture Hall",
    "Literature Building",
    "Information Center - North Point Entrance",
    "Guava",
    "Cellular and Molecular Medicine East",
    "Robinson Building 2 - Auditorium",
    "Robinson Building 3 - Library",
    "Molli and Arthur Wagner Dance Building",
    "Gilman Parking",
    "Keck Oceanographic and Atmospheric Research - 3",
    "Science and Engineering Research Facility",
    "University Center 104",
    "University Center 105",
    "University Center 106",
    "University Center 107",
    "University Center 109",
    "University Center 110",
    "Landscape Services Trailer",
    "Deep Sea Drilling West",
    "Deep Sea Drilling East",
    "Hubbs Hall",
    "Isaacs Hall",
    "Birch Aquarium at Scripps",
    "Nori",
    "Nierenberg Hall",
    "Ocean Drilling Program Core Building",
    "Anne Ratner Children's Eye Center",
    "T-25 Cottage",
    "Martin Johnson House",
    "T-30 Cottage",
    "T-31 Cottage",
    "Electromagnetics Research Facility",
    "Geodesic Dome 1",
    "Geodesic Dome 2",
    "Powell Structural Components Laboratory",
    "Fred N. Spiess Hall",
    "Old Director's House",
    "Biology Field Station - Greenhouse 1",
    "Biology Field Station - Greenhouse 2",
    "Biology Field Station - Greenhouse 3",
    "Biology Field Station - Main Building",
    "Biology Field Station - Laboratory and Growing Rooms",
    "Biology Field Station - Jerboa",
    "Biology Field Station - Frog House",
    "Environmental Management Facility",
    "Campus Services Complex - Building A",
    "Campus Emergency Services Building",
    "Campus Services Complex - Building C",
    "Campus Services Complex - Building D",
    "Campus Services Complex - Building H",
    "Mayer Hall Addition",
    "Biology Field Station - Greenhouse 4",
    "Old Scripps",
    "Eckart Building",
    "Scripps Pier Laboratory",
    "Marine Science Development Center - Building B",
    "Lifeguard Tower",
    "San Diego Supercomputer Office Addition",
    "Marine Science Development Center - Building C",
    "3366 North Torrey Pines Court",
    "Ritter Hall",
    "Marine Science Development Center - Building D",
    "Early Childhood Education Center A",
    "Early Childhood Education Center C",
    "Early Childhood Education Center B",
    "Early Childhood Education Center D",
    "Warren Residence Hall - Harlan",
    "Warren Residence Hall - Frankfurter",
    "Warren Residence Hall - Stewart",
    "Warren Apartments - Brown",
    "Warren Apartments - Bates",
    "Canyon Vista",
    "IGPP 1000 - Revelle Laboratory",
    "IGPP 2000 - Revelle Laboratory",
    "IGPP 3000 - Revelle Laboratory",
    "IGPP 4000 - Revelle Laboratory",
    "Powell-Focht Bioengineering Hall",
    "CSC Shops",
    "Fleet Services",
    "Marine Science Development Center - Building A",
    "Gildred Latin American Studies Building",
    "Copley International Conference Center",
    "Sverdrup Hall",
    "New Scripps Administration",
    "Kaplan Lab",
    "Sumner Auditorium",
    "Urey Hall Office Addition",
    "Central Utilities Plant",
    "Urey Hall",
    "Center for Coastal Studies",
    "9321 Discovery Way",
    "9331 Discovery Way",
    "9355 Discovery Way",
    "9369 Discovery Way",
    "9383 Discovery Way",
    "9393 Discovery Way",
    "9310 Redwood Drive",
    "9334 Redwood Drive",
    "9344 Redwood Drive",
    "9350 Redwood Drive",
    "9366 Redwood Drive",
    "9388 Redwood Drive",
    "Mayer Hall",
    "Bonner Hall",
    "IGPP - Munk Laboratory",
    "Pacific Hall",
    "East Campus Substation",
    "Galbraith Hall",
    "64 Degrees",
    "Hydraulics Laboratory",
    "Scholander Hall",
    "York Hall",
    "Corallina",
    "Revelle College Provost Office",
    "Torrey Pines Center North - Parking",
    "Torrey Pines Center North",
    "Torrey Pines Center South",
    "Structural and Materials Engineering Building",
    "School of Medicine Building 2",
    "University Center 302",
    "University Center 409",
    "University Center 201",
    "University Center 202",
    "University Center 301",
    "University Center 301A",
    "University Center 401",
    "University Center 400",
    "Student Services Center",
    "Center Hall",
    "101 Marshall College",
    "Thomas Wayland Vaughan Hall",
    "Leichtag Family Foundation Biomedical Research Building",
    "University Center 111",
    "University Center 108",
    "University Center 303",
    "Warren Student Activity Center",
    "Camp Snoopy Res Hall 710 (H)",
    "Camp Snoopy Res Hall 709 (G)",
    "Camp Snoopy Res Hall 708 (F)",
    "Camp Snoopy Res Hall 707 (E)",
    "Camp Snoopy Res Hall 706 (D)",
    "Camp Snoopy Res Hall 705 (C)",
    "Camp Snoopy Res Hall 704 (B)",
    "Camp Snoopy Res Hall 703 (A)",
    "789 Camp Snoopy",
    "Biomedical Sciences Building",
    "9238 Central Mesa Apartments (W. Laundry)",
    "9126 South Mesa Apartments (Laundry)",
    "Recreation Gymnasium",
    "Revelle Residence Hall - Beagle",
    "Revelle Residence Hall - Challenger",
    "Revelle Residence Hall - Discovery",
    "Revelle Residence Hall - Atlantis",
    "Revelle Residence Hall - Meteor",
    "Revelle Residence Hall - Galathea",
    "Revelle Residence Hall - Argo",
    "Revelle Residence Hall - Blake",
    "Natatorium",
    "Main Gymnasium",
    "W. M. Keck Building",
    "Pepper Canyon Apartments Lodge",
    "Visual Arts Facility - Building 1",
    "Visual Arts Facility - Building 2",
    "Visual Arts Facility - Building 3",
    "Visual Arts Facility - Building 4",
    "Visual Arts Facility - Building 5",
    "Visual Arts Facility - Building 6",
    "Guava Extension",
    "Computer Science and Engineering Building",
    "Electric Shop",
    "Moores Cancer Center",
    "Roger Revelle Student Center",
    "East Campus Utilities Plant",
    "Spanos Athletic Training Facility",
    "Ida and Cecil Green Faculty Club",
    "Deep Sea Drilling Building C",
    "Mandeville Center",
    "Geisel Library",
    "Applied Physics and Mathematics",
    "Biology Building",
    "McGill Hall",
    "Humanities and Social Sciences",
    "Muir Residence Hall - Tenaya",
    "Muir Residence Hall - Tioga",
    "Roots and Pines",
    "Tuolumne Apartments - S House Laundry",
    "Student Center A - Building H",
    "Student Health and Wellness Center",
    "Social Sciences Research Building",
    "Cognitive Science Building",
    "Solis Hall",
    "Communication Building",
    "Eucalyptus Point",
    "Fireside Lounge",
    "Goody's Place",
    "Marshall College Dean's Residence",
    "Ocean View Terrace",
    "Extended Studies and Public Programs - Building A",
    "Extended Studies and Public Programs - Building B",
    "Extended Studies and Public Programs - Building C",
    "Extended Studies and Public Programs - Building D",
    "Extended Studies and Public Programs - Building E",
    "Extended Studies and Public Programs - Building F",
    "Extended Studies and Public Programs - Building H",
    "Extended Studies and Public Programs - Building J",
    "Extended Studies and Public Programs - Building K",
    "Extended Studies and Public Programs - Building M",
    "Extended Studies and Public Programs - Building N",
    "Extended Studies and Public Programs - Building O - East",
    "Extended Studies and Public Programs - Building O - West",
    "Extended Studies and Public Programs - Building G",
    "Atkinson Hall",
    "Natural Sciences Building",
    "Skaggs Pharmaceutical Sciences Building",
    "Hamilton Glaucoma and Jacobs Retina Center",
    "Triton Athletic Training",
    "102 Marshall College",
    "103 Marshall College",
    "103A Marshall College",
    "Otterson Hall",
    "University Center 611",
    "Student Center A - Building ES",
    "Price Center West",
    "Student Center B",
    "Student Center Pub",
    "Canyonview Aquatic and Climbing Wall Facility",
    "East Campus Shuttle Operations Modular",
    "Mandell Weiss Forum",
    "Mandell Weiss Theatre",
    "Mandell Weiss Theatre Shop",
    "Roots and Pines Annex",
    "Ivy",
    "Holly",
    "Jacaranda",
    "Extended Studies and Public Programs - Building X",
    "Extended Studies and Public Programs - Building Y",
    "Extended Studies and Public Programs - Building Z",
    "Satellite Utility Plant",
    "Keck Oceanographic and Atmospheric Research - 1",
    "Keck Oceanographic and Atmospheric Research - 2",
    "Pepper Canyon Hall",
    "Shiley Eye Expansion",
    "Hopkins Parking",
    "Institute of the Americas Addition",
    "Conrad Prebys Music Center",
    "Transit Operations Trailer",
    "Thurgood Marshall College Administration Building",
    "Economics Building",
    "Social Sciences Building",
    "Holly Addition",
    "Kalmia",
    "Laurel",
    "Magnolia",
    "Sequoyah Hall",
    "Marshall Upper Apartments - G",
    "Eelgrass",
    "ROCKWEED",
    "LIMU",
    "Foodworx",
    "Price Center East Expansion",
    "RIMAC Annex",
    "Marine Conservation and Technology Facility",
    "James' Place",
    "Extended Studies and Public Programs - Building L",
    "Student Center A - Building A",
    "Student Center A - Building EN",
    "Revelle 12KV Switching Station",
    "Roosevelt Residence Hall - Middle East",
    "Veterans Affairs Medical Center",
    "Roosevelt Residence Hall - Oceania",
    "Roosevelt Residence Hall - Earth",
    "Camp Snoopy Student Services",
    "Camp Snoopy Dean's Residence",
    "ERC Laundry South",
    "Roosevelt Residence Hall - North America",
    "Roosevelt Residence Hall - Latin America",
    "Roosevelt Residence Hall - Europe",
    "Roosevelt Residence Hall - Asia",
    "Roosevelt Residence Hall - Africa",
    "Cafe Ventanas",
    "ERC Administration North",
    "ERC Administration South",
    "Pangea Parking",
    "Roosevelt Residence Hall - Mesa Verde N",
    "Roosevelt Residence Hall - Mesa Verde S",
    "Roosevelt Residence Hall - Geneva E",
    "Roosevelt Residence Hall - Geneva W",
    "ERC Laundry East",
    "Roosevelt Residence Hall - Kathmandu E",
    "Roosevelt Residence Hall - Kathmandu W",
    "Roosevelt Residence Hall - Cuzco E",
    "Roosevelt Residence Hall - Cuzco W",
    "Roosevelt Residence Hall - Asante E",
    "Roosevelt Residence Hall - Asante W",
    "Asante House Meeting Rooms",
    "Great Hall",
    "Mesa Support A",
    "Mesa Support B",
    "Mesa Support C",
    "Faculty Club Expansion",
    "One Miramar Street, Parking Garage",
    "One Miramar Street - 1",
    "One Miramar Street - 2",
    "One Miramar Street - 3",
    "One Miramar Street - 4",
    "One Miramar Street, Building 5",
    "Price Center South Expansion",
    "Extended Studies and Public Programs - Building P",
    "Rita Atkinson Residences",
    "ERC Pump House",
    "Laurel Extension",
    "Central Research Services",
    "Anne Ratner Children's Eye Center Expansion",
    "Jacobs Medical Center - Bed Tower",
    "Biomedical Research Facility II",
    "Student Center A - Building C",
    "Student Center A - Building F",
    "Student Center A - Building G",
    "Splash Cafe at Birch Aquarium",
    "9350A Coast Apartments",
    "Campus Point Parking Structure West",
    "Campus Point Parking Structure East",
    "Marine Ecosystem Sensing, Observation and Modeling",
    "East Campus Office Building",
    "Robert Paine Scripps Forum for Science, Society and the Environment - Auditorium",
    "Robert Paine Scripps Seaside Forum Meeting Rooms",
    "Robert Paine Scripps Seaside Forum Service Building",
    "Altman Clinical Translational Research Institute",
    "East Campus Medical Center Central Plant",
    "Radiation Oncology PET/CT Center",
    "Pepper Canyon Apartments 100",
    "Pepper Canyon Apartments 200",
    "Pepper Canyon Apartments 300",
    "Pepper Canyon Apartments 400",
    "Pepper Canyon Apartments 500",
    "Pepper Canyon Apartments 600",
    "Pepper Canyon Apartments 700",
    "Pepper Canyon Apartments 800",
    "Pepper Canyon Apartments 900",
    "Pepper Canyon Apartments 1000",
    "Pepper Canyon Apartments 1100",
    "Pepper Canyon Apartments 1200",
    "Pepper Canyon Apartments 1300",
    "Pepper Canyon Apartments 1400",
    "Pepper Canyon Apartments 1500",
    "Pepper Canyon Apartments 1600",
    "Pepper Canyon Apartments 1700",
    "Pepper Canyon Apartments 1800",
    "Pepper Canyon North Laundry",
    "Pepper Canyon South Laundry",
    "Matthews Apartments A",
    "Matthews Apartments B",
    "Matthews Apartments C",
    "Matthews Apartments D",
    "Matthews Apartments E",
    "Matthews Housing Maintenance Carpentry Shop",
    "Matthews Maintenance and Lounge",
    "Marshall Lower Apartments - A",
    "Marshall Lower Apartments - B",
    "Marshall Lower Apartments - C",
    "Marshall Lower Apartments - D",
    "Marshall Lower Apartments - E",
    "Marshall Lower Apartments - F",
    "Marshall Upper Apartments - H",
    "Marshall Upper Apartments - J",
    "Marshall Upper Apartments - K",
    "Marshall Upper Apartments - L",
    "Marshall Upper Apartments - M",
    "Marshall Residence Hall - N",
    "Marshall Residence Hall - O",
    "Marshall Residence Hall - P",
    "Marshall Residence Hall - Q",
    "Marshall Residence Hall - R",
    "Marshall Residence Hall - S",
    "Marshall Residence Hall - T",
    "Marshall Residence Hall - U",
    "Marshall Residence Hall - V",
    "Tuolumne Apartments - S House North",
    "Tuolumne Apartments - S House West",
    "Tuolumne Apartments - S House South",
    "Tuolumne Apartments - S House East",
    "Tuolumne Apartments - T House North",
    "Tuolumne Apartments - T House West",
    "Tuolumne Apartments - T House South",
    "Tuolumne Apartments - T House East",
    "Warren Apartments - Black",
    "Warren Apartments - Brennan",
    "Warren Apartments - Douglas",
    "Warren Apartments - Goldberg",
    "Mesa Apartments Central - 9226",
    "Mesa Apartments Central - 9228",
    "Mesa Apartments Central - 9230",
    "Mesa Apartments Central - 9232",
    "Mesa Apartments Central - 9234",
    "Mesa Apartments Central - 9236",
    "Mesa Apartments Central - 9240",
    "Mesa Apartments Central - 9242",
    "Mesa Apartments Central - 9244",
    "Mesa Apartments Central - 9246",
    "Mesa Apartments Central - 9248",
    "Mesa Apartments Central - 9250",
    "Mesa Apartments Central - 9252",
    "Mesa Apartments Central - 9254",
    "Mesa Apartments Central - 9256",
    "Mesa Apartments Central - 9258",
    "Mesa Apartments Central - 9260",
    "Mesa Apartments Central - 9262",
    "9264 Central Mesa Apartments (Laundry)",
    "Mesa Apartments Central - 9266",
    "Mesa Apartments Central - 9268",
    "Mesa Apartments Central - 9270",
    "Mesa Apartments South - 9100",
    "Mesa Apartments South - 9106",
    "Mesa Apartments South - 9114",
    "Mesa Apartments South - 9118",
    "Mesa Apartments South - 9122",
    "Mesa Apartments South - 9130",
    "Mesa Apartments South - 9134",
    "Mesa Apartments South - 9138",
    "Mesa Apartments South - 9142",
    "Mesa Apartments South - 9146",
    "Mesa Apartments South - 9148",
    "Mesa Apartments South - 9152",
    "9156 South Mesa Apartments (Laundry)",
    "Mesa Apartments South - 9160",
    "Mesa Apartments South - 9162",
    "Mesa Apartments South - 9168",
    "Mesa Apartments South - 9172",
    "Mesa Apartments South - 9176",
    "Mesa Apartments South - 9180",
    "9184 South Mesa Apartments (Laundry)",
    "Mesa Apartments South - 9188",
    "Mesa Apartments South - 9192",
    "Biomedical Sciences Building Addition",
    "Mandler Hall",
    "Canyonview Filter Facility",
    "Student Health and Wellness Expansion",
    "Sulpizio Family Cardiovascular Center",
    "Seventh West - 1",
    "Seventh West - 2",
    "Seventh West - 3",
    "Seventh West - 4",
    "Seventh West - 5",
    "Seventh West - 6",
    "Seventh West - 7",
    "San Diego Supercomputer East Expansion",
    "Seventh West - 8",
    "Wells Fargo Hall",
    "Compressed Natural Gas Fueling",
    "Pepper Canyon Asst Dean Res",
    "Tata Hall",
    "Housing, Dining and Hospitality Services",
    "Pepper Canyon Switching Station",
    "T. Denny Sanford Medical Education and Telemedicine Center",
    "Revelle Apartments - Keeling 1",
    "Revelle Apartments - Keeling 2",
    "Revelle Apartments - Keeling 3",
    "Warren Pump House",
    "Seventh East - 1",
    "Seventh East - 2",
    "Seventh East - 3",
    "Seventh East - 4",
    "Seventh East - 5",
    "Seventh East - 6",
    "Seventh East - 7",
    "Medical Center Modular 1",
    "Medical Center Modular 2",
    "Muir Apartments - Tamarack W",
    "Muir Apartments - Tamarack E",
    "Preuss Trailer 1",
    "Preuss Modular Classroom West",
    "Preuss Modular Classroom East",
    "Sanford Consortium for Regenerative Medicine",
    "Athena Parking",
    "Telecommunications Node B",
    "Medical Center Switching Station",
    "SIO New Director's Office",
    "Koman Family Outpatient Pavilion",
    "Center for Translational Imaging and Precision Medicine",
    "Triton Stadium",
    "Triton Clubhouse",
    "Spanos Athletic Performance Center",
    "NOAA Southwest Fisheries Science Center",
    "East Campus Utilities Plant Expansion",
    "Environmental Management Facility 2",
    "Osler Parking",
    "Mesa Nueva - Ola",
    "Mesa Nueva - Cala",
    "Mesa Nueva - Arena",
    "Mesa Nueva - Cresta",
    "Mesa Nueva - Artesa",
    "Mesa Nueva - Marea",
    "Nuevo West - Viento",
    "Nuevo West - Marketplace",
    "Nuevo West - Brisa",
    "3333 North Torrey Pines Court",
    "3344 North Torrey Pines Court",
    "3377 North Torrey Pines Court",
    "10350 North Torrey Pines Road",
    "9435 Modular Offices",
    "Foodworx Dining Room",
    "J. Craig Venter Institute",
    "La Jolla Institute for Allergy And Immunology",
    "Center For Novel Therapeutics",
    "Nuevo West Parking",
    "Nuevo East - Tierra",
    "Nuevo East - Astilla",
    "Nuevo East - Exchange",
    "Nuevo East - Porton",
    "Nuevo East - Capa",
    "Nuevo East - Piedra",
    "Thornton Supplemental Storage",
    "Campus Curbside",
    "NTPLL - Catalyst",
    "NTPLL - Kaleidoscope",
    "NTPLL - Tapestry",
    "NTPLL - Mosaic",
    "NTPLL - GA Auditorium",
    "Mobile PET/CT Scanner",
    "MRI Trailer",
    "Outback Adventures",
    "Preuss School - Building F",
    "Preuss School - Building A",
    "Preuss School - Building B",
    "Preuss School - Building C",
    "Preuss School - Building D",
    "Preuss School - Building E",
    "NTPLLN Ridgewalk - Public Engagement Building",
    "NTPLLN Ridgewalk - Arts & Humanities"
  ],
  onSelect: () => {}
};